
name: Hello Flow
on:
  push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hello World! A cada Push"
      - name: Diga valeu
        run: echo "Valeu - bye! Pushei e tchau"
        